version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "vts91/backend"
    networks:
      - mynet
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    image: "vts91/frontend"
    networks:
      - mynet
    ports:
      - "3000:3000"
    links:
      - "backend"
networks:
  mynet:
    driver: bridge